// 1 using UnityEngine;
// 2 L using System. Collections;
// 3
// 4â‚½ public class FauxGravityBody : MonoBehaviour {
//     public FauxGravityAttractor attractor;
//     private Transform myTransform;
//     void Start () {
//         rigidbody.constraints = RigidbodyConstraints.FreezeRotation;
//         rigidbody.useGravity = false;
//         myTransform = transform;
//         9 F-
//             10
//         11
//         12
//         13
//         14
//         15 B
//         16
//         18 L;
//         19
//         void Update () {
//             attractor. Attract (myTransform);
//         }